# Generated by Django 2.2.7 on 2020-01-12 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=20)),
            ],
            options={
                'db_table': 'Question_Type',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=20)),
                ('time', models.IntegerField(blank=True, db_column='Time', null=True)),
                ('max_marks', models.IntegerField(db_column='Max_Marks')),
                ('pass_marks', models.IntegerField(db_column='Passing_Marks')),
                ('tutor_id', models.ForeignKey(db_column='Tutor_Id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Quiz',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_text', models.CharField(db_column='Question_Text', max_length=100)),
                ('q_image', models.ImageField(db_column='Question_Image', upload_to='images/question/')),
                ('q_video', models.CharField(db_column='Question_Video', max_length=100)),
                ('q_type', models.IntegerField(db_column='Question_Type')),
                ('a_text', models.CharField(db_column='Option1_Text', max_length=100)),
                ('a_image', models.ImageField(db_column='Option1_Image', upload_to='images/option/')),
                ('a_video', models.CharField(db_column='Option1_Video', max_length=100)),
                ('b_text', models.CharField(db_column='Option2_Text', max_length=100)),
                ('b_image', models.ImageField(db_column='Option2_Image', upload_to='images/option/')),
                ('b_video', models.CharField(db_column='Option2_Video', max_length=100)),
                ('c_text', models.CharField(db_column='Option3_Text', max_length=100)),
                ('c_image', models.ImageField(db_column='Option3_Image', upload_to='images/option/')),
                ('c_video', models.CharField(db_column='Option3_Video', max_length=100)),
                ('d_text', models.CharField(db_column='Option4_Text', max_length=100)),
                ('d_image', models.ImageField(db_column='Option4_Image', upload_to='images/option/')),
                ('d_video', models.CharField(db_column='Option4_Video', max_length=100)),
                ('quiz_id', models.ForeignKey(db_column='Quiz_Id', on_delete=django.db.models.deletion.CASCADE, to='main.Quiz')),
            ],
            options={
                'db_table': 'Question',
            },
        ),
    ]
