# Generated by Django 2.2.7 on 2020-01-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_question_questiontype_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(db_column='Answer', default=2, max_length=20),
            preserve_default=False,
        ),
    ]
