# Generated by Django 2.2.7 on 2020-01-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='no_questions',
            field=models.IntegerField(db_column='Number_Questions', default=1),
            preserve_default=False,
        ),
    ]
